name = "md"
version = "1.0.0"
license = "MIT"
author = "marvinfriede"
copyright = "Copyright 2022, Marvin Friede"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
